/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Capsule {
  'id' : string,
  'creator' : Principal,
  'content' : CapsuleContent,
  'metadata' : CapsuleMetadata,
  'encrypted' : boolean,
  'picture' : [] | [ExternalBlob],
}
export type CapsuleContent = {
    'predictionCapsule' : {
      'prediction' : string,
      'explanation' : [] | [string],
      'category' : PredictionCategory,
      'commitId' : string,
      'confidence' : [] | [bigint],
    }
  } |
  {
    'loveCapsule' : {
      'note' : [] | [string],
      'message' : string,
      'category' : LoveCategory,
    }
  };
export interface CapsuleMetadata {
  'createdAtTimestamp' : [] | [Timestamp],
  'capsuleType' : CapsuleType,
  'createdAt' : Time,
  'vaultKeyHash' : string,
  'unlockAt' : Time,
  'claimCode' : string,
}
export type CapsuleType = { 'prediction' : null } |
  { 'love' : null };
export type CapsuleVerificationStatus = { 'verified' : null } |
  { 'notVerified' : null } |
  { 'unknownLegacy' : null };
export type ExternalBlob = Uint8Array;
export interface FailedVerificationLog {
  'failureReason' : string,
  'enteredCode' : string,
  'normalizedCode' : string,
  'environmentChecked' : string,
}
export interface FeedbackEntry {
  'id' : bigint,
  'approvalStatus' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'comment' : string,
  'deviceId' : string,
  'timestamp' : Time,
}
export interface FeedbackResponse {
  'allFeedback' : Array<FeedbackEntry>,
  'message' : string,
  'feedbackEntry' : FeedbackEntry,
}
export type LoveCategory = { 'appreciation' : null } |
  { 'encouragement' : null } |
  { 'apology' : null } |
  { 'reflection' : null } |
  { 'celebration' : null };
export type PredictionCategory = { 'money' : null } |
  { 'life' : null } |
  { 'work' : null } |
  { 'personal' : null } |
  { 'sportsEvents' : null };
export type Response = { 'error' : string } |
  { 'success' : Array<Capsule> };
export type Response_1 = { 'error' : string } |
  { 'success' : Capsule };
export type Time = bigint;
export interface Timestamp {
  'timezone' : string,
  'date' : string,
  'time' : string,
}
export interface UserProfile { 'name' : string, 'vaultKeyHash' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPicture' : ActorMethod<[string, ExternalBlob], undefined>,
  'approveFeedback' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkCapsuleExpiry' : ActorMethod<[string], boolean>,
  'checkHealth' : ActorMethod<[], boolean>,
  'createCapsule' : ActorMethod<
    [string, CapsuleContent, CapsuleMetadata],
    undefined
  >,
  'deleteCapsule' : ActorMethod<[string], undefined>,
  'getAllCapsules' : ActorMethod<[], Array<Capsule>>,
  'getAllFeedback' : ActorMethod<[], Array<FeedbackEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCapsule' : ActorMethod<[string], Capsule>,
  'getCapsuleSafe' : ActorMethod<[string], Response_1>,
  'getCapsulesByVaultKey' : ActorMethod<[string], Array<Capsule>>,
  'getCapsulesByVaultKeySafe' : ActorMethod<[string], Response>,
  'getFailedVerificationLogs' : ActorMethod<[], Array<FailedVerificationLog>>,
  'getPicture' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectFeedback' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitFeedback' : ActorMethod<[string, string], FeedbackResponse>,
  'verifyAllCapsules' : ActorMethod<
    [],
    Array<[string, [] | [string], [] | [CapsuleVerificationStatus]]>
  >,
  'verifyCapsule' : ActorMethod<
    [string, [] | [string]],
    [] | [CapsuleVerificationStatus]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];