/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PredictionCategory = IDL.Variant({
  'money' : IDL.Null,
  'life' : IDL.Null,
  'work' : IDL.Null,
  'personal' : IDL.Null,
  'sportsEvents' : IDL.Null,
});
export const LoveCategory = IDL.Variant({
  'appreciation' : IDL.Null,
  'encouragement' : IDL.Null,
  'apology' : IDL.Null,
  'reflection' : IDL.Null,
  'celebration' : IDL.Null,
});
export const CapsuleContent = IDL.Variant({
  'predictionCapsule' : IDL.Record({
    'prediction' : IDL.Text,
    'explanation' : IDL.Opt(IDL.Text),
    'category' : PredictionCategory,
    'commitId' : IDL.Text,
    'confidence' : IDL.Opt(IDL.Nat),
  }),
  'loveCapsule' : IDL.Record({
    'note' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'category' : LoveCategory,
  }),
});
export const Timestamp = IDL.Record({
  'timezone' : IDL.Text,
  'date' : IDL.Text,
  'time' : IDL.Text,
});
export const CapsuleType = IDL.Variant({
  'prediction' : IDL.Null,
  'love' : IDL.Null,
});
export const Time = IDL.Int;
export const CapsuleMetadata = IDL.Record({
  'createdAtTimestamp' : IDL.Opt(Timestamp),
  'capsuleType' : CapsuleType,
  'createdAt' : Time,
  'vaultKeyHash' : IDL.Text,
  'unlockAt' : Time,
  'claimCode' : IDL.Text,
});
export const Capsule = IDL.Record({
  'id' : IDL.Text,
  'creator' : IDL.Principal,
  'content' : CapsuleContent,
  'metadata' : CapsuleMetadata,
  'encrypted' : IDL.Bool,
  'picture' : IDL.Opt(ExternalBlob),
});
export const FeedbackEntry = IDL.Record({
  'id' : IDL.Nat,
  'approvalStatus' : IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'comment' : IDL.Text,
  'deviceId' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'vaultKeyHash' : IDL.Opt(IDL.Text),
});
export const Response_1 = IDL.Variant({
  'error' : IDL.Text,
  'success' : Capsule,
});
export const Response = IDL.Variant({
  'error' : IDL.Text,
  'success' : IDL.Vec(Capsule),
});
export const FailedVerificationLog = IDL.Record({
  'failureReason' : IDL.Text,
  'enteredCode' : IDL.Text,
  'normalizedCode' : IDL.Text,
  'environmentChecked' : IDL.Text,
});
export const FeedbackResponse = IDL.Record({
  'allFeedback' : IDL.Vec(FeedbackEntry),
  'message' : IDL.Text,
  'feedbackEntry' : FeedbackEntry,
});
export const CapsuleVerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'notVerified' : IDL.Null,
  'unknownLegacy' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPicture' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'approveFeedback' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkCapsuleExpiry' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'checkHealth' : IDL.Func([], [IDL.Bool], ['query']),
  'createCapsule' : IDL.Func(
      [IDL.Text, CapsuleContent, CapsuleMetadata],
      [],
      [],
    ),
  'deleteCapsule' : IDL.Func([IDL.Text], [], []),
  'getAllCapsules' : IDL.Func([], [IDL.Vec(Capsule)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCapsule' : IDL.Func([IDL.Text], [Capsule], ['query']),
  'getCapsuleSafe' : IDL.Func([IDL.Text], [Response_1], ['query']),
  'getCapsulesByVaultKey' : IDL.Func([IDL.Text], [IDL.Vec(Capsule)], ['query']),
  'getCapsulesByVaultKeySafe' : IDL.Func([IDL.Text], [Response], ['query']),
  'getFailedVerificationLogs' : IDL.Func(
      [],
      [IDL.Vec(FailedVerificationLog)],
      ['query'],
    ),
  'getPicture' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectFeedback' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text], [FeedbackResponse], []),
  'verifyAllCapsules' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Opt(IDL.Text),
            IDL.Opt(CapsuleVerificationStatus),
          )
        ),
      ],
      ['query'],
    ),
  'verifyCapsule' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Opt(CapsuleVerificationStatus)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PredictionCategory = IDL.Variant({
    'money' : IDL.Null,
    'life' : IDL.Null,
    'work' : IDL.Null,
    'personal' : IDL.Null,
    'sportsEvents' : IDL.Null,
  });
  const LoveCategory = IDL.Variant({
    'appreciation' : IDL.Null,
    'encouragement' : IDL.Null,
    'apology' : IDL.Null,
    'reflection' : IDL.Null,
    'celebration' : IDL.Null,
  });
  const CapsuleContent = IDL.Variant({
    'predictionCapsule' : IDL.Record({
      'prediction' : IDL.Text,
      'explanation' : IDL.Opt(IDL.Text),
      'category' : PredictionCategory,
      'commitId' : IDL.Text,
      'confidence' : IDL.Opt(IDL.Nat),
    }),
    'loveCapsule' : IDL.Record({
      'note' : IDL.Opt(IDL.Text),
      'message' : IDL.Text,
      'category' : LoveCategory,
    }),
  });
  const Timestamp = IDL.Record({
    'timezone' : IDL.Text,
    'date' : IDL.Text,
    'time' : IDL.Text,
  });
  const CapsuleType = IDL.Variant({
    'prediction' : IDL.Null,
    'love' : IDL.Null,
  });
  const Time = IDL.Int;
  const CapsuleMetadata = IDL.Record({
    'createdAtTimestamp' : IDL.Opt(Timestamp),
    'capsuleType' : CapsuleType,
    'createdAt' : Time,
    'vaultKeyHash' : IDL.Text,
    'unlockAt' : Time,
    'claimCode' : IDL.Text,
  });
  const Capsule = IDL.Record({
    'id' : IDL.Text,
    'creator' : IDL.Principal,
    'content' : CapsuleContent,
    'metadata' : CapsuleMetadata,
    'encrypted' : IDL.Bool,
    'picture' : IDL.Opt(ExternalBlob),
  });
  const FeedbackEntry = IDL.Record({
    'id' : IDL.Nat,
    'approvalStatus' : IDL.Variant({
      'pending' : IDL.Null,
      'approved' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'comment' : IDL.Text,
    'deviceId' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'vaultKeyHash' : IDL.Opt(IDL.Text),
  });
  const Response_1 = IDL.Variant({ 'error' : IDL.Text, 'success' : Capsule });
  const Response = IDL.Variant({
    'error' : IDL.Text,
    'success' : IDL.Vec(Capsule),
  });
  const FailedVerificationLog = IDL.Record({
    'failureReason' : IDL.Text,
    'enteredCode' : IDL.Text,
    'normalizedCode' : IDL.Text,
    'environmentChecked' : IDL.Text,
  });
  const FeedbackResponse = IDL.Record({
    'allFeedback' : IDL.Vec(FeedbackEntry),
    'message' : IDL.Text,
    'feedbackEntry' : FeedbackEntry,
  });
  const CapsuleVerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'notVerified' : IDL.Null,
    'unknownLegacy' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPicture' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'approveFeedback' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkCapsuleExpiry' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'checkHealth' : IDL.Func([], [IDL.Bool], ['query']),
    'createCapsule' : IDL.Func(
        [IDL.Text, CapsuleContent, CapsuleMetadata],
        [],
        [],
      ),
    'deleteCapsule' : IDL.Func([IDL.Text], [], []),
    'getAllCapsules' : IDL.Func([], [IDL.Vec(Capsule)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCapsule' : IDL.Func([IDL.Text], [Capsule], ['query']),
    'getCapsuleSafe' : IDL.Func([IDL.Text], [Response_1], ['query']),
    'getCapsulesByVaultKey' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Capsule)],
        ['query'],
      ),
    'getCapsulesByVaultKeySafe' : IDL.Func([IDL.Text], [Response], ['query']),
    'getFailedVerificationLogs' : IDL.Func(
        [],
        [IDL.Vec(FailedVerificationLog)],
        ['query'],
      ),
    'getPicture' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectFeedback' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text], [FeedbackResponse], []),
    'verifyAllCapsules' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Opt(IDL.Text),
              IDL.Opt(CapsuleVerificationStatus),
            )
          ),
        ],
        ['query'],
      ),
    'verifyCapsule' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Opt(CapsuleVerificationStatus)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };