/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Capsule {
    id: string;
    creator: Principal;
    content: CapsuleContent;
    metadata: CapsuleMetadata;
    encrypted: boolean;
    picture?: ExternalBlob;
}
export interface Timestamp {
    timezone: string;
    date: string;
    time: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type CapsuleContent = {
    __kind__: "predictionCapsule";
    predictionCapsule: {
        prediction: string;
        explanation?: string;
        category: PredictionCategory;
        commitId: string;
        confidence?: bigint;
    };
} | {
    __kind__: "loveCapsule";
    loveCapsule: {
        note?: string;
        message: string;
        category: LoveCategory;
    };
};
export interface FailedVerificationLog {
    failureReason: string;
    enteredCode: string;
    normalizedCode: string;
    environmentChecked: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FeedbackEntry {
    id: bigint;
    approvalStatus: Variant_pending_approved_rejected;
    comment: string;
    deviceId: string;
    timestamp: Time;
}
export interface FeedbackResponse {
    allFeedback: Array<FeedbackEntry>;
    message: string;
    feedbackEntry: FeedbackEntry;
}
export interface CapsuleMetadata {
    createdAtTimestamp?: Timestamp;
    capsuleType: CapsuleType;
    createdAt: Time;
    vaultKeyHash: string;
    unlockAt: Time;
    claimCode: string;
}
export type Response_1 = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: Capsule;
};
export type Response = {
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: Array<Capsule>;
};
export interface UserProfile {
    name: string;
    vaultKeyHash?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CapsuleType {
    prediction = "prediction",
    love = "love"
}
export enum CapsuleVerificationStatus {
    verified = "verified",
    notVerified = "notVerified",
    unknownLegacy = "unknownLegacy"
}
export enum LoveCategory {
    appreciation = "appreciation",
    encouragement = "encouragement",
    apology = "apology",
    reflection = "reflection",
    celebration = "celebration"
}
export enum PredictionCategory {
    money = "money",
    life = "life",
    work = "work",
    personal = "personal",
    sportsEvents = "sportsEvents"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPicture(capsuleId: string, picture: ExternalBlob): Promise<void>;
    approveFeedback(feedbackId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkCapsuleExpiry(capsuleId: string): Promise<boolean>;
    checkHealth(): Promise<boolean>;
    createCapsule(id: string, content: CapsuleContent, metadata: CapsuleMetadata): Promise<void>;
    deleteCapsule(capsuleId: string): Promise<void>;
    getAllCapsules(): Promise<Array<Capsule>>;
    getAllFeedback(): Promise<Array<FeedbackEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCapsule(capsuleId: string): Promise<Capsule>;
    getCapsuleSafe(capsuleId: string): Promise<Response_1>;
    getCapsulesByVaultKey(vaultKeyHash: string): Promise<Array<Capsule>>;
    getCapsulesByVaultKeySafe(vaultKeyHash: string): Promise<Response>;
    getFailedVerificationLogs(): Promise<Array<FailedVerificationLog>>;
    getPicture(capsuleId: string): Promise<ExternalBlob | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    rejectFeedback(feedbackId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitFeedback(deviceId: string, comment: string): Promise<FeedbackResponse>;
    verifyAllCapsules(): Promise<Array<[string, string | null, CapsuleVerificationStatus | null]>>;
    verifyCapsule(claimCode: string, commitId: string | null): Promise<CapsuleVerificationStatus | null>;
}
import type { Capsule as _Capsule, CapsuleContent as _CapsuleContent, CapsuleMetadata as _CapsuleMetadata, CapsuleType as _CapsuleType, CapsuleVerificationStatus as _CapsuleVerificationStatus, ExternalBlob as _ExternalBlob, FeedbackEntry as _FeedbackEntry, FeedbackResponse as _FeedbackResponse, LoveCategory as _LoveCategory, PredictionCategory as _PredictionCategory, Response as _Response, Response_1 as _Response_1, Time as _Time, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPicture(arg0: string, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPicture(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPicture(arg0, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async approveFeedback(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveFeedback(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkCapsuleExpiry(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkCapsuleExpiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkCapsuleExpiry(arg0);
            return result;
        }
    }
    async checkHealth(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkHealth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkHealth();
            return result;
        }
    }
    async createCapsule(arg0: string, arg1: CapsuleContent, arg2: CapsuleMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCapsule(arg0, to_candid_CapsuleContent_n11(this._uploadFile, this._downloadFile, arg1), to_candid_CapsuleMetadata_n19(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCapsule(arg0, to_candid_CapsuleContent_n11(this._uploadFile, this._downloadFile, arg1), to_candid_CapsuleMetadata_n19(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteCapsule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCapsule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCapsule(arg0);
            return result;
        }
    }
    async getAllCapsules(): Promise<Array<Capsule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCapsules();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCapsules();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeedback(): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCapsule(arg0: string): Promise<Capsule> {
        if (this.processError) {
            try {
                const result = await this.actor.getCapsule(arg0);
                return from_candid_Capsule_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCapsule(arg0);
            return from_candid_Capsule_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCapsuleSafe(arg0: string): Promise<Response_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCapsuleSafe(arg0);
                return from_candid_Response_1_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCapsuleSafe(arg0);
            return from_candid_Response_1_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCapsulesByVaultKey(arg0: string): Promise<Array<Capsule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCapsulesByVaultKey(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCapsulesByVaultKey(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCapsulesByVaultKeySafe(arg0: string): Promise<Response> {
        if (this.processError) {
            try {
                const result = await this.actor.getCapsulesByVaultKeySafe(arg0);
                return from_candid_Response_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCapsulesByVaultKeySafe(arg0);
            return from_candid_Response_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFailedVerificationLogs(): Promise<Array<FailedVerificationLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFailedVerificationLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFailedVerificationLogs();
            return result;
        }
    }
    async getPicture(arg0: string): Promise<ExternalBlob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPicture(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPicture(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectFeedback(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFeedback(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFeedback(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n55(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitFeedback(arg0: string, arg1: string): Promise<FeedbackResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1);
                return from_candid_FeedbackResponse_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1);
            return from_candid_FeedbackResponse_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyAllCapsules(): Promise<Array<[string, string | null, CapsuleVerificationStatus | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAllCapsules();
                return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAllCapsules();
            return from_candid_vec_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyCapsule(arg0: string, arg1: string | null): Promise<CapsuleVerificationStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyCapsule(arg0, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyCapsule(arg0, to_candid_opt_n64(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CapsuleContent_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CapsuleContent): CapsuleContent {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_CapsuleMetadata_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CapsuleMetadata): CapsuleMetadata {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_CapsuleType_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CapsuleType): CapsuleType {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_CapsuleVerificationStatus_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CapsuleVerificationStatus): CapsuleVerificationStatus {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
async function from_candid_Capsule_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Capsule): Promise<Capsule> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FeedbackEntry_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackEntry): FeedbackEntry {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_FeedbackResponse_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackResponse): FeedbackResponse {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_LoveCategory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoveCategory): LoveCategory {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_PredictionCategory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictionCategory): PredictionCategory {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_Response_1_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Response_1): Promise<Response_1> {
    return await from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
async function from_candid_Response_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Response): Promise<Response> {
    return await from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CapsuleVerificationStatus]): CapsuleVerificationStatus | null {
    return value.length === 0 ? null : from_candid_CapsuleVerificationStatus_n62(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    creator: Principal;
    content: _CapsuleContent;
    metadata: _CapsuleMetadata;
    encrypted: boolean;
    picture: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    creator: Principal;
    content: CapsuleContent;
    metadata: CapsuleMetadata;
    encrypted: boolean;
    picture?: ExternalBlob;
}> {
    return {
        id: value.id,
        creator: value.creator,
        content: from_candid_CapsuleContent_n26(_uploadFile, _downloadFile, value.content),
        metadata: from_candid_CapsuleMetadata_n35(_uploadFile, _downloadFile, value.metadata),
        encrypted: value.encrypted,
        picture: record_opt_to_undefined(await from_candid_opt_n40(_uploadFile, _downloadFile, value.picture))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prediction: string;
    explanation: [] | [string];
    category: _PredictionCategory;
    commitId: string;
    confidence: [] | [bigint];
}): {
    prediction: string;
    explanation?: string;
    category: PredictionCategory;
    commitId: string;
    confidence?: bigint;
} {
    return {
        prediction: value.prediction,
        explanation: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.explanation)),
        category: from_candid_PredictionCategory_n30(_uploadFile, _downloadFile, value.category),
        commitId: value.commitId,
        confidence: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.confidence))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    note: [] | [string];
    message: string;
    category: _LoveCategory;
}): {
    note?: string;
    message: string;
    category: LoveCategory;
} {
    return {
        note: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.note)),
        message: value.message,
        category: from_candid_LoveCategory_n33(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAtTimestamp: [] | [_Timestamp];
    capsuleType: _CapsuleType;
    createdAt: _Time;
    vaultKeyHash: string;
    unlockAt: _Time;
    claimCode: string;
}): {
    createdAtTimestamp?: Timestamp;
    capsuleType: CapsuleType;
    createdAt: Time;
    vaultKeyHash: string;
    unlockAt: Time;
    claimCode: string;
} {
    return {
        createdAtTimestamp: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.createdAtTimestamp)),
        capsuleType: from_candid_CapsuleType_n38(_uploadFile, _downloadFile, value.capsuleType),
        createdAt: value.createdAt,
        vaultKeyHash: value.vaultKeyHash,
        unlockAt: value.unlockAt,
        claimCode: value.claimCode
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    approvalStatus: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    comment: string;
    deviceId: string;
    timestamp: _Time;
}): {
    id: bigint;
    approvalStatus: Variant_pending_approved_rejected;
    comment: string;
    deviceId: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        approvalStatus: from_candid_variant_n45(_uploadFile, _downloadFile, value.approvalStatus),
        comment: value.comment,
        deviceId: value.deviceId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    vaultKeyHash: [] | [string];
}): {
    name: string;
    vaultKeyHash?: string;
} {
    return {
        name: value.name,
        vaultKeyHash: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.vaultKeyHash))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    allFeedback: Array<_FeedbackEntry>;
    message: string;
    feedbackEntry: _FeedbackEntry;
}): {
    allFeedback: Array<FeedbackEntry>;
    message: string;
    feedbackEntry: FeedbackEntry;
} {
    return {
        allFeedback: from_candid_vec_n42(_uploadFile, _downloadFile, value.allFeedback),
        message: value.message,
        feedbackEntry: from_candid_FeedbackEntry_n43(_uploadFile, _downloadFile, value.feedbackEntry)
    };
}
function from_candid_tuple_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, [] | [string], [] | [_CapsuleVerificationStatus]]): [string, string | null, CapsuleVerificationStatus | null] {
    return [
        value[0],
        from_candid_opt_n29(_uploadFile, _downloadFile, value[1]),
        from_candid_opt_n61(_uploadFile, _downloadFile, value[2])
    ];
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    predictionCapsule: {
        prediction: string;
        explanation: [] | [string];
        category: _PredictionCategory;
        commitId: string;
        confidence: [] | [bigint];
    };
} | {
    loveCapsule: {
        note: [] | [string];
        message: string;
        category: _LoveCategory;
    };
}): {
    __kind__: "predictionCapsule";
    predictionCapsule: {
        prediction: string;
        explanation?: string;
        category: PredictionCategory;
        commitId: string;
        confidence?: bigint;
    };
} | {
    __kind__: "loveCapsule";
    loveCapsule: {
        note?: string;
        message: string;
        category: LoveCategory;
    };
} {
    return "predictionCapsule" in value ? {
        __kind__: "predictionCapsule",
        predictionCapsule: from_candid_record_n28(_uploadFile, _downloadFile, value.predictionCapsule)
    } : "loveCapsule" in value ? {
        __kind__: "loveCapsule",
        loveCapsule: from_candid_record_n32(_uploadFile, _downloadFile, value.loveCapsule)
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    money: null;
} | {
    life: null;
} | {
    work: null;
} | {
    personal: null;
} | {
    sportsEvents: null;
}): PredictionCategory {
    return "money" in value ? PredictionCategory.money : "life" in value ? PredictionCategory.life : "work" in value ? PredictionCategory.work : "personal" in value ? PredictionCategory.personal : "sportsEvents" in value ? PredictionCategory.sportsEvents : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    appreciation: null;
} | {
    encouragement: null;
} | {
    apology: null;
} | {
    reflection: null;
} | {
    celebration: null;
}): LoveCategory {
    return "appreciation" in value ? LoveCategory.appreciation : "encouragement" in value ? LoveCategory.encouragement : "apology" in value ? LoveCategory.apology : "reflection" in value ? LoveCategory.reflection : "celebration" in value ? LoveCategory.celebration : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prediction: null;
} | {
    love: null;
}): CapsuleType {
    return "prediction" in value ? CapsuleType.prediction : "love" in value ? CapsuleType.love : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: _Capsule;
}): Promise<{
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: Capsule;
}> {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: await from_candid_Capsule_n24(_uploadFile, _downloadFile, value.success)
    } : value;
}
async function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    error: string;
} | {
    success: Array<_Capsule>;
}): Promise<{
    __kind__: "error";
    error: string;
} | {
    __kind__: "success";
    success: Array<Capsule>;
}> {
    return "error" in value ? {
        __kind__: "error",
        error: value.error
    } : "success" in value ? {
        __kind__: "success",
        success: await from_candid_vec_n23(_uploadFile, _downloadFile, value.success)
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    notVerified: null;
} | {
    unknownLegacy: null;
}): CapsuleVerificationStatus {
    return "verified" in value ? CapsuleVerificationStatus.verified : "notVerified" in value ? CapsuleVerificationStatus.notVerified : "unknownLegacy" in value ? CapsuleVerificationStatus.unknownLegacy : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Capsule>): Promise<Array<Capsule>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Capsule_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedbackEntry>): Array<FeedbackEntry> {
    return value.map((x)=>from_candid_FeedbackEntry_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, [] | [string], [] | [_CapsuleVerificationStatus]]>): Array<[string, string | null, CapsuleVerificationStatus | null]> {
    return value.map((x)=>from_candid_tuple_n60(_uploadFile, _downloadFile, x));
}
function to_candid_CapsuleContent_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CapsuleContent): _CapsuleContent {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_CapsuleMetadata_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CapsuleMetadata): _CapsuleMetadata {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_CapsuleType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CapsuleType): _CapsuleType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LoveCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoveCategory): _LoveCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PredictionCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PredictionCategory): _PredictionCategory {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    note?: string;
    message: string;
    category: LoveCategory;
}): {
    note: [] | [string];
    message: string;
    category: _LoveCategory;
} {
    return {
        note: value.note ? candid_some(value.note) : candid_none(),
        message: value.message,
        category: to_candid_LoveCategory_n14(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    prediction: string;
    explanation?: string;
    category: PredictionCategory;
    commitId: string;
    confidence?: bigint;
}): {
    prediction: string;
    explanation: [] | [string];
    category: _PredictionCategory;
    commitId: string;
    confidence: [] | [bigint];
} {
    return {
        prediction: value.prediction,
        explanation: value.explanation ? candid_some(value.explanation) : candid_none(),
        category: to_candid_PredictionCategory_n17(_uploadFile, _downloadFile, value.category),
        commitId: value.commitId,
        confidence: value.confidence ? candid_some(value.confidence) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAtTimestamp?: Timestamp;
    capsuleType: CapsuleType;
    createdAt: Time;
    vaultKeyHash: string;
    unlockAt: Time;
    claimCode: string;
}): {
    createdAtTimestamp: [] | [_Timestamp];
    capsuleType: _CapsuleType;
    createdAt: _Time;
    vaultKeyHash: string;
    unlockAt: _Time;
    claimCode: string;
} {
    return {
        createdAtTimestamp: value.createdAtTimestamp ? candid_some(value.createdAtTimestamp) : candid_none(),
        capsuleType: to_candid_CapsuleType_n21(_uploadFile, _downloadFile, value.capsuleType),
        createdAt: value.createdAt,
        vaultKeyHash: value.vaultKeyHash,
        unlockAt: value.unlockAt,
        claimCode: value.claimCode
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    vaultKeyHash?: string;
}): {
    name: string;
    vaultKeyHash: [] | [string];
} {
    return {
        name: value.name,
        vaultKeyHash: value.vaultKeyHash ? candid_some(value.vaultKeyHash) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "predictionCapsule";
    predictionCapsule: {
        prediction: string;
        explanation?: string;
        category: PredictionCategory;
        commitId: string;
        confidence?: bigint;
    };
} | {
    __kind__: "loveCapsule";
    loveCapsule: {
        note?: string;
        message: string;
        category: LoveCategory;
    };
}): {
    predictionCapsule: {
        prediction: string;
        explanation: [] | [string];
        category: _PredictionCategory;
        commitId: string;
        confidence: [] | [bigint];
    };
} | {
    loveCapsule: {
        note: [] | [string];
        message: string;
        category: _LoveCategory;
    };
} {
    return value.__kind__ === "predictionCapsule" ? {
        predictionCapsule: to_candid_record_n16(_uploadFile, _downloadFile, value.predictionCapsule)
    } : value.__kind__ === "loveCapsule" ? {
        loveCapsule: to_candid_record_n13(_uploadFile, _downloadFile, value.loveCapsule)
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LoveCategory): {
    appreciation: null;
} | {
    encouragement: null;
} | {
    apology: null;
} | {
    reflection: null;
} | {
    celebration: null;
} {
    return value == LoveCategory.appreciation ? {
        appreciation: null
    } : value == LoveCategory.encouragement ? {
        encouragement: null
    } : value == LoveCategory.apology ? {
        apology: null
    } : value == LoveCategory.reflection ? {
        reflection: null
    } : value == LoveCategory.celebration ? {
        celebration: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PredictionCategory): {
    money: null;
} | {
    life: null;
} | {
    work: null;
} | {
    personal: null;
} | {
    sportsEvents: null;
} {
    return value == PredictionCategory.money ? {
        money: null
    } : value == PredictionCategory.life ? {
        life: null
    } : value == PredictionCategory.work ? {
        work: null
    } : value == PredictionCategory.personal ? {
        personal: null
    } : value == PredictionCategory.sportsEvents ? {
        sportsEvents: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CapsuleType): {
    prediction: null;
} | {
    love: null;
} {
    return value == CapsuleType.prediction ? {
        prediction: null
    } : value == CapsuleType.love ? {
        love: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
